apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service-deploy
  labels:
    app: ml-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ml-service
  template:
    metadata:
      labels:
        project: ml-service
    spec:
      containers:
        - name: ml-service
          image: ilyazawyalowww/ml_service:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ml-service-service
  labels:
    owner: IlyaZawyalow
spec:
  selector:
    project: ml-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort