apiVersion: apps/v1
kind: Deployment
metadata:
  name: parsing-service-deploy
  labels:
    app: parsing-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      project: parsing-service
  template:
    metadata:
      labels:
        project: parsing-service
    spec:
      containers:
        - name: parsing-service
          image: ilyazawyalowww/parsing_service:v1
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: parsing-service-service
  labels:
    owner: IlyaZawyalow
spec:
  selector:
    project: parsing-service
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8000
  type: NodePort