apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service-deploy
  labels:
    app: ui-service
spec:
  replicas: 1
  selector:
    matchLabels:
      project: ui-service
  template:
    metadata:
      labels:
        project: ui-service
    spec:
      containers:
        - name: ui-service
          image: ilyazawyalowww/ui_service:v8
          ports:
            - containerPort: 80
          env:
            - name: PARSING_SERVICE_URL
              value: "http://parsing-service-service.default.svc.cluster.local:81"
            - name: ML_SERVICE_URL
              value: "http://ml-service-service.default.svc.cluster.local:80"

---
apiVersion: v1
kind: Service
metadata:
  name: ui-service-service
  labels:
    owner: IlyaZawyalow
spec:
  selector:
    project: ui-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: NodePort
